// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm51N37XtmunBgYBLNDKK1o6kNAbARW44',
    appId: '1:662650052724:web:652fda09be517eaad03121',
    messagingSenderId: '662650052724',
    projectId: 'oga-home',
    authDomain: 'oga-home.firebaseapp.com',
    storageBucket: 'oga-home.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnHwbaAAu-TOUjyplglZiaGqygHxsakJM',
    appId: '1:662650052724:android:4057c99871ed2cded03121',
    messagingSenderId: '662650052724',
    projectId: 'oga-home',
    storageBucket: 'oga-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwmKJQO7RkmEn_lImnhmvi6NT6PP5vR3Y',
    appId: '1:662650052724:ios:13d3509b66442362d03121',
    messagingSenderId: '662650052724',
    projectId: 'oga-home',
    storageBucket: 'oga-home.firebasestorage.app',
    androidClientId: '662650052724-nj54qg7flghh3ffrepaphtjiml7hetj9.apps.googleusercontent.com',
    iosClientId: '662650052724-lqmqm04n8un62731tibct2djdj2i470e.apps.googleusercontent.com',
    iosBundleId: 'ar.com.vanguardia.craftr.craftrMobile',
  );

}